package threads;

public class ResultTask extends Thread {
    public void run() {
        System.out.println("Result generated by:" +
                Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t = new ResultTask();
        t.run();//Normal Excution -> Always the main thread
        t.start();//Multi Threading --> T-0,T-1, and so on
        //start() internally calls run()
        //Thread cannot be started twice

    }
}
